name: Build APK with Buildozer (Autogen Spec)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip openjdk-17-jdk git python3-pip build-essential \
            autoconf automake libtool pkg-config libffi-dev \
            libssl-dev libncurses5-dev libncursesw5-dev libsqlite3-dev \
            libjpeg-dev zlib1g-dev libgl1-mesa-dev libgles2-mesa-dev \
            libtiff5-dev libpng-dev libx11-dev libxcursor-dev libxrandr-dev \
            libxinerama-dev libxi-dev xclip wget curl

      - name: Install Buildozer and Cython
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Cache buildozer .buildozer folder
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}

      - name: Create .buildozer if not exists
        run: mkdir -p .buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: bin/*.apk
